name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
defaults:
  run:
    working-directory: ./Horse Isle Server

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet publish -r linux-x64 --self-contained false
    - name: upload result
      uses: actions/upload-artifact@v2
      with:
        name: result
        path: Horse Isle Server/HorseIsleServer/bin/Debug/net5.0/linux-x64/publish/
